/* @@@LICENSE
 *
 * Copyright (c) 2020-2025 SPARC Laboratory, HUST.
 * Copyright (c) 2023-2025 Phung Ba Truong Giang.
 *
 * LICENSE@@@ */


/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change.
*/

#include <QtQml/qqmlextensionplugin.h>

Q_IMPORT_QML_PLUGIN(contentPlugin)
Q_IMPORT_QML_PLUGIN(UntitledProjectPlugin)
